spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: AuthorService
  cloud:
      config:
          uri: http://localhost:8888
          name: AuthorService
